apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nginx-gateway
spec:
  selector:
    istio: ingressgateway # usa o pod IngressGateway padrão do Istio
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "website.rs-ceschi.com.br"
